/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SucessoRouteImport } from './routes/sucesso'
import { Route as PixRouteImport } from './routes/pix'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'

const SucessoRoute = SucessoRouteImport.update({
  id: '/sucesso',
  path: '/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const PixRoute = PixRouteImport.update({
  id: '/pix',
  path: '/pix',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/pix': typeof PixRoute
  '/sucesso': typeof SucessoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/pix': typeof PixRoute
  '/sucesso': typeof SucessoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/pix': typeof PixRoute
  '/sucesso': typeof SucessoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/checkout' | '/pix' | '/sucesso'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/checkout' | '/pix' | '/sucesso'
  id: '__root__' | '/' | '/checkout' | '/pix' | '/sucesso'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  PixRoute: typeof PixRoute
  SucessoRoute: typeof SucessoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sucesso': {
      id: '/sucesso'
      path: '/sucesso'
      fullPath: '/sucesso'
      preLoaderRoute: typeof SucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pix': {
      id: '/pix'
      path: '/pix'
      fullPath: '/pix'
      preLoaderRoute: typeof PixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  PixRoute: PixRoute,
  SucessoRoute: SucessoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
